### ISSUE TITLE
sprite error for svgs created with sketch

### ISSUE THREAD

**Issue by bencooling** [drdk/grunt-dr-svg-sprites#21]
I have created multiple svg files in bohemian codings sketch app. I run the grunt-dr-svg-sprites task but it generates a sprite file that renders:

This page contains the following errors:
... Namespace prefix sketch for type on path is not defined

Is there a way around this?
Thanks

**Comment by hiulit** [comment]
Isn't this issue already fixed?

I'm using Sketch for creating the SVGs and I don't have any problem using this plugin...

**Comment by rasmusfl0e** [comment]
Yeah - I think the to features I added (namespace-support and `options.svgo`) did the trick :)
