### ISSUE TITLE
Lots of good ideas and improvements

### ISSUE THREAD

**Issue by hiulit** [drdk/grunt-dr-svg-sprites#44]
I've recently come across this article https://www.liquidlight.co.uk/blog/article/creating-svg-sprites-using-gulp-and-sass/ and I think we could take some ideas from this plugin.

* Sass mixins & functions
* Sass templates
* Sass placeholders

I know, basically, it's adding better Sass support, but I guess it would make sense since it's the most used pre-processor. And these features would make this plugin more flexible and useful.

**Comment by rasmusfl0e** [comment]
I'm not familiar enough with Sass to feel I could write/maintain what you're suggesting - but you are more than welcome to build a complementary Sass-suite or something that uses dr-svg-sprites under the hood :)

**Comment by hiulit** [comment]
I'll take a deeper look and I'll let you know ;)
